### ISSUE TITLE
Accept custom error message instead of statusText?

### ISSUE THREAD

**Issue by talum** [snags88/wtfetch#1]
It'd be awesome if we could provide a custom error message [here](https://github.com/snags88/wtfetch/blob/master/src/util/response-helpers.js#L6). What do ya think?

**Comment by snags88** [comment]
@talum would you be able to pass the custom error message from the server side as `statusText` as the key in the response?

**Comment by talum** [comment]
Hm that's a good question @snags88. I can try it out. [Docs](https://developer.mozilla.org/en-US/docs/Web/API/Response/statusText) said it was read-only, but I'm down to give it a shot.

Ah, some more thoughts: 🤔 https://github.com/github/fetch/issues/565

**Comment by snags88** [comment]
@talum Sorry, didn't get a notification on your comment. I don't know if you resolved this issue, but if you send back an error in the response object, it should be attached to the error object that is thrown [here](https://github.com/snags88/wtfetch/blob/master/src/util/response-helpers.js#L7)

**Comment by talum** [comment]
Ah, no worries. Yeah, I messed around with it, and it wasn't quite working that way. Also, we probably have to use a different polyfill pretty soon. Just a heads up...unless you wanna work on it with us 😉. So I'mma close this.
